### ISSUE TITLE
My measurements

### ISSUE THREAD

**Issue by buybackoff** [nietras/1brc.cs#2]
Sorry if I made you feel uncomfortable or something...

Let's discuss my measurements here.

I have just spent some time updating your repo to this and making it work again on Linux
![image](https://github.com/nietras/1brc.cs/assets/489852/9eb0deba-cf0e-456c-964a-af549288b4dd)

But the results were nothing like I had in the preliminary section of my table. (And yes, it was nothing more than **preliminary** results).

I now see you are quite active right now and maybe be I did run some bad commit. 

Please tell me when I could re-run everything from the master head.

**Comment by nietras** [comment]
@buybackoff thank you for reaching out. I hope I have fixed the issues you have reported, I've added CI to confirm main now works on all platforms, windows, macos, linux. Currently I am trying to test that 17GB file but an issue on windows it is generated with \r\n line endings, not \n. So replacing line endings in 17GB file is an issue. I can't run WSL currently because I've disabled SVM in BIOS and Hyper-V to try to get hardware counters... so yeah issues.

> But the results were nothing like I had in the preliminary section of my table. (And yes, it was nothing more than preliminary results).

Are you saying they were disappointing? On Windows at least the normal "measurements-1000000000.txt" is still less than 1 second vs 2 seconds for yours.

**Comment by nietras** [comment]
Code works on the 17GB 1B 10k real station names, but it is definitely not optimized for it, so my take on that clearly isn't that good (3x slower than the normal), but I haven't measured or tuned it. So will look at that some later time.

![image](https://github.com/nietras/1brc.cs/assets/10798831/913df7f9-9000-4591-b4f4-9804c5991e6e)

**Comment by buybackoff** [comment]
So, if I just pull the main branch now is it the thing we want to measure?

> Are you saying they were disappointing?

Yes, they were at 3.2 secs vs. 2.04 in the blog table.

> On Windows at least the normal "measurements-1000000000.txt" is still less than 1 second vs 2 seconds for yours.

I could eventually run everything on Windows VM on the same host. But for the last week I did not even try to run the big data set on Windows. It's good for Dev, not for Prod.

Do you have an idea why that particular commit may be slower than before on the default dataset?

**Comment by buybackoff** [comment]
> Code works on the 17GB 1B 10k ...

But that alone qualifies you to be the top .NET in the cheaters' dataset scenario 🤣

**Comment by nietras** [comment]
> Do you have an idea why that particular commit may be slower than before on the default dataset?

No that makes no sense to me. As far as I know you are running on x64 right? That commit only falls back for macos/arm CI testing.

I haven't tested on Linux but only thing that should be changed is the switch to RandomAccess, of course that may work differently on linux. You can run both with BenchmarkDotNet via the `bench.ps1` command (or contents it), this of course requires data to be in a specific path. I don't have a real option for testing on a proper linux machine myself sadly.

> But that alone qualifies you to be the top .NET in the cheaters' dataset scenario 🤣

Right, but that scenario also heavily favors impls that can handle short names fast since +50% are <4 bytes long.

**Comment by nietras** [comment]
@buybackoff thank you for updating your blog, closing this, feel free to contact me if anything new or similar.
